using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Nodes;
using Microsoft.DurableTask;
using Microsoft.DurableTask.Client;

namespace DC.CopyProyectFromTemplate.Functions;

/// <summary>
/// The status link handed out in the 202 and the body ImportStatusResponder answers with.
/// Kept apart from the HTTP trigger so it can be tested without a Durable host.
/// </summary>
public static class ImportStatusBody
{
    private const int MaxInstanceIdLength = 100;

    /// <summary>
    /// Durable instance ids generated by this app are 32 hex characters. Anything outside letters,
    /// digits, '-' and '_' is refused before it reaches the task hub.
    /// </summary>
    public static bool IsValidInstanceId([NotNullWhen(true)] string? instanceId)
    {
        return !string.IsNullOrEmpty(instanceId)
            && instanceId.Length <= MaxInstanceIdLength
            && instanceId.All(character => char.IsAsciiLetterOrDigit(character) || character == '-' || character == '_');
    }

    /// <summary>
    /// The status link for an operation started by <paramref name="requestUrl"/>: the same address
    /// with the instance id appended, which a GET on the same function answers, so the caller's
    /// function key works for both. The query string is dropped, so a ?code= key the caller sent
    /// is never echoed back.
    ///
    /// Scheme and host come from the Forwarded header, then X-Forwarded-Proto and X-Forwarded-Host,
    /// then the request itself: the order the Durable extension uses for statusQueryGetUri, because
    /// behind the App Service front end and the Functions host the worker can see an internal address.
    /// </summary>
    public static Uri StatusUri(
        Uri requestUrl,
        string instanceId,
        string? forwarded = null,
        string? forwardedProto = null,
        string? forwardedHost = null)
    {
        Dictionary<string, string> forwardedElement = ParseForwarded(forwarded);

        string scheme = KnownScheme(forwardedElement.GetValueOrDefault("proto"))
            ?? KnownScheme(FirstListValue(forwardedProto))
            ?? requestUrl.Scheme;
        string authority = forwardedElement.GetValueOrDefault("host")
            ?? FirstListValue(forwardedHost)
            ?? requestUrl.Authority;

        if (!Uri.TryCreate(scheme + "://" + authority, UriKind.Absolute, out Uri? origin) || !IsPlainOrigin(origin))
        {
            // A malformed forwarded host must not break the link: fall back to what the request says.
            origin = new Uri(requestUrl.GetLeftPart(UriPartial.Authority));
        }

        UriBuilder builder = new UriBuilder(origin.Scheme, origin.Host, origin.Port)
        {
            Path = requestUrl.AbsolutePath.TrimEnd('/') + "/" + Uri.EscapeDataString(instanceId)
        };

        return builder.Uri;
    }

    /// <summary>The key/value pairs of the first element of a Forwarded header (RFC 7239).</summary>
    private static Dictionary<string, string> ParseForwarded(string? forwarded)
    {
        Dictionary<string, string> values = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        string? element = FirstListValue(forwarded);

        if (element == null)
        {
            return values;
        }

        foreach (string pair in element.Split(';'))
        {
            int separator = pair.IndexOf('=');

            if (separator <= 0)
            {
                continue;
            }

            string value = pair.Substring(separator + 1).Trim().Trim('"');

            if (value.Length > 0)
            {
                values.TryAdd(pair.Substring(0, separator).Trim(), value);
            }
        }

        return values;
    }

    /// <summary>The first entry of a comma-separated header, which the proxy closest to the client wrote.</summary>
    private static string? FirstListValue(string? header)
    {
        string? first = header?.Split(',')[0].Trim();
        return string.IsNullOrEmpty(first) ? null : first;
    }

    private static string? KnownScheme(string? scheme)
    {
        if (string.Equals(scheme, "https", StringComparison.OrdinalIgnoreCase))
        {
            return "https";
        }

        return string.Equals(scheme, "http", StringComparison.OrdinalIgnoreCase) ? "http" : null;
    }

    private static bool IsPlainOrigin(Uri origin)
    {
        return origin.AbsolutePath == "/"
            && origin.UserInfo.Length == 0
            && origin.Query.Length == 0
            && origin.Fragment.Length == 0;
    }

    /// <summary>
    /// The instance id of a status address, {prefix}/{route}/{instanceId}, or null when the address
    /// ends at the route itself. The route is compared ignoring case, like the host's routing.
    /// </summary>
    public static string? InstanceIdFromPath(Uri requestUrl, string route)
    {
        string[] segments = requestUrl.AbsolutePath.Trim('/').Split('/');
        int last = segments.Length - 1;

        if (string.Equals(segments[last], route, StringComparison.OrdinalIgnoreCase))
        {
            return null;
        }

        return last >= 1 && string.Equals(segments[last - 1], route, StringComparison.OrdinalIgnoreCase)
            ? Uri.UnescapeDataString(segments[last])
            : null;
    }

    /// <summary>Whether the operation was started by the given orchestrator, so by that endpoint.</summary>
    public static bool BelongsTo(OrchestrationMetadata metadata, string orchestratorName)
    {
        return string.Equals(metadata.Name, orchestratorName, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>Pending, Running, Suspended and ContinuedAsNew still have work ahead.</summary>
    public static bool IsFinished(OrchestrationRuntimeStatus status)
    {
        // ContinuedAsNew is obsolete but can still be reported by older runtimes; it is not finished.
#pragma warning disable CS0618
        return status is not (OrchestrationRuntimeStatus.Pending
            or OrchestrationRuntimeStatus.Running
            or OrchestrationRuntimeStatus.Suspended
            or OrchestrationRuntimeStatus.ContinuedAsNew);
#pragma warning restore CS0618
    }

    /// <summary>
    /// { id, runtimeStatus, createdTime, lastUpdatedTime, customStatus, output, error }.
    /// The input is never included: it names the uploaded blob and the resource decisions.
    /// </summary>
    public static JsonObject Build(OrchestrationMetadata metadata)
    {
        bool failed = metadata.RuntimeStatus == OrchestrationRuntimeStatus.Failed;

        return new JsonObject
        {
            ["id"] = metadata.InstanceId,
            ["runtimeStatus"] = metadata.RuntimeStatus.ToString(),
            ["createdTime"] = metadata.CreatedAt,
            ["lastUpdatedTime"] = metadata.LastUpdatedAt,
            ["customStatus"] = ParseCamelCase(metadata.SerializedCustomStatus),
            ["output"] = failed ? null : ParseCamelCase(metadata.SerializedOutput),
            ["error"] = failed ? FailureMessage(metadata) : null
        };
    }

    /// <summary>
    /// Why an orchestration failed, in the order of how much the caller can do with it: the deepest
    /// failure message, then the orchestration output (where the extension puts the exception text
    /// when it sends no failure details), then at least the exception type.
    /// </summary>
    public static string? FailureMessage(OrchestrationMetadata metadata)
    {
        string? message = InnermostMessage(metadata.FailureDetails);

        if (!string.IsNullOrWhiteSpace(message))
        {
            return message;
        }

        message = FromSerializedOutput(metadata.SerializedOutput);

        if (!string.IsNullOrWhiteSpace(message))
        {
            return message;
        }

        string? type = metadata.FailureDetails?.ErrorType;

        return string.IsNullOrWhiteSpace(type)
            ? "The operation failed without an error message."
            : $"The operation failed ({type}) without an error message.";
    }

    /// <summary>
    /// The text of a failed orchestration's output: a JSON string or plain text, cut to what comes
    /// after "failed with an unhandled exception:" (the activity's own message) and to 1000 characters.
    /// </summary>
    public static string? FromSerializedOutput(string? serialized)
    {
        if (string.IsNullOrWhiteSpace(serialized))
        {
            return null;
        }

        string text = serialized.Trim();

        try
        {
            if (JsonNode.Parse(text) is JsonValue value && value.TryGetValue(out string? parsed) && parsed != null)
            {
                text = parsed.Trim();
            }
        }
        catch (JsonException)
        {
            // Plain text, not JSON: used as it is.
        }

        const string marker = "failed with an unhandled exception: ";
        int index = text.LastIndexOf(marker, StringComparison.Ordinal);

        if (index >= 0)
        {
            text = text[(index + marker.Length)..].Trim();
        }

        if (text.Length == 0)
        {
            return null;
        }

        return text.Length > 1000 ? text[..1000] : text;
    }

    /// <summary>
    /// The deepest non-empty message: the orchestration only says an activity failed, the
    /// activity's own exception says why.
    /// </summary>
    public static string? InnermostMessage(TaskFailureDetails? failure)
    {
        string? message = null;

        for (TaskFailureDetails? current = failure; current != null; current = current.InnerFailure)
        {
            if (!string.IsNullOrWhiteSpace(current.ErrorMessage))
            {
                message = current.ErrorMessage.Trim();
            }
        }

        return message;
    }

    /// <summary>
    /// Parses a serialized output or custom status and turns its property names into camelCase,
    /// so clients read tasksCreated whatever naming policy the Durable data converter used.
    /// Text that is not JSON comes back as a string.
    /// </summary>
    public static JsonNode? ParseCamelCase(string? serialized)
    {
        if (string.IsNullOrWhiteSpace(serialized))
        {
            return null;
        }

        JsonNode? node;

        try
        {
            node = JsonNode.Parse(serialized);
        }
        catch (JsonException)
        {
            return JsonValue.Create(serialized);
        }

        return ToCamelCase(node);
    }

    private static JsonNode? ToCamelCase(JsonNode? node)
    {
        switch (node)
        {
            case JsonObject jsonObject:
                JsonObject renamed = new JsonObject();

                foreach (KeyValuePair<string, JsonNode?> property in jsonObject)
                {
                    renamed[JsonNamingPolicy.CamelCase.ConvertName(property.Key)] = ToCamelCase(property.Value);
                }

                return renamed;

            case JsonArray jsonArray:
                JsonArray items = new JsonArray();

                foreach (JsonNode? item in jsonArray)
                {
                    items.Add(ToCamelCase(item));
                }

                return items;

            default:
                return node?.DeepClone();
        }
    }
}
